---
title: "P8105_hw01_XF2226"
author: "Xin Fang"
date: "9/26/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r problem 1 - create a new data frame}

problem1_tibble <- tibble(
  random_sample = rnorm(10), #a random sample of size 10 from a standard Normal distribution
  vec_logical = random_sample > 0, #a logical vector indicating whether elements of the sample are greater than 0
  vec_character = c("a","b","c","d","e","f","g","h","j","k"), #a character vector of length 10
  vec_factor = factor(c("a","b","c", "a","b","c","a","b","c","a"), levels = c("a","b","c")) #a factor vector of length 10, with 3 different factor “levels” - a,b,c
)

```

```{r problem1 - Test if mean of each variable in problem1_tibble works}

mean(pull(problem1_tibble,random_sample)) #mean works because this is a numeric vector

mean(pull(problem1_tibble,vec_logical)) #mean works because for a logical vector, TRUE is considered as 1 and FALSE is considered as 0.

mean(pull(problem1_tibble,vec_character)) #mean does NOT work because this is a character vector

mean(pull(problem1_tibble,vec_factor)) #mean does NOT work because this is a factor vector with levels

```
```{r problem 1 - apply as.numeric to each variable in problem1_tibble, echo=TRUE, results='hide'}
as.numeric(pull(problem1_tibble,vec_logical)) #as.numeric works because for a logical vector, TRUE is considered as 1 and FALSE is considered as 0. The logical vector can be created as type numeric. This explains why the mean function works. 

as.numeric(pull(problem1_tibble,vec_character)) #NAs introduced, because this a character vector, which cannot be coerced into type numeric. This explains why the mean function did not work. 

as.numeric(pull(problem1_tibble,vec_factor)) #The output tells us that in this factor vector, "a" is level 1, "b" is level 2, "c" is level 3. This factor vector can be coerced into type numeric. This does not explain why the mean function did not work. However, we know that the mean function does not work because this is still a factor vector with 3 levels of "a", "b", and "c" and we cannot take the mean of a factor vector like this. 

```

```{r problem 2 }

data("penguins", package = "palmerpenguins")

```

